### ISSUE TITLE
Ctypes doesn't work in IronPython 2.7.6.0 with Mono 3.12.1 on Ubuntu 14.04

### ISSUE THREAD

**Issue by christianimhorst** [IronLanguages/main#1146]
Hi,

Ctypes doesn't work in IronPython 2.7.6.0 with Mono 3.12.1 on Ubuntu 14.04:

$ ipy -V
PythonContext 2.7.6.0 on 3.12.1 (master/6299445 Do 13. Nov 20:44:44 CET 2014)
$ mono --version
Mono JIT compiler version 3.12.1 (master/6299445 Do 13. Nov 20:44:44 CET 2014)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty
$ ipy
IronPython 2.7.6a0 (2.7.6.0) on Mono 4.0.30319.17020 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.

import ctypes
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/IronLanguages/External.LCA_RESTRICTED/Languages/IronPython/27/Lib/ctypes/__init__.py", line 441, in <module>
  File "/opt/IronLanguages/External.LCA_RESTRICTED/Languages/IronPython/27/Lib/ctypes/__init__.py", line 353, in __init__
OSError: IronPython.Runtime.Exceptions.OSException: cannot load library 
  at IronPython.Modules.CTypes.LoadLibrary (System.String library, Int32 mode) [0x00000] in <filename unknown>:0 
  at IronPython.Modules.CTypes.dlopen (System.String library, Int32 mode) [0x00000] in <filename unknown>:0 
  at Microsoft.Scripting.Interpreter.FuncCallInstruction`3[System.String,System.Int32,System.Object].Run (Microsoft.Scripting.Interpreter.InterpretedFrame frame) [0x00000] in <filename unknown>:0 
  at Microsoft.Scripting.Interpreter.Interpreter.Run (Microsoft.Scripting.Interpreter.InterpretedFrame frame) [0x00000] in <filename unknown>:0 

Best regards
Christian

**Comment by slide** [comment]
Please reopen if there is still an issue (probably is) on a newer version of Mono.
