### ISSUE TITLE
Encoding UTF-32-BE is missing from the IronPython standard library.

### ISSUE THREAD

**Issue by phijaro** [IronLanguages/main#1212]
In CPython, Jython or PyPy:

```python
>>> 'foo'.encode('utf-32-be')
'\x00\x00\x00f\x00\x00\x00o\x00\x00\x00o'
>>>
```

In IronPython, however:

```python
IronPython 2.7.5 (2.7.5.0) on .NET 4.0.30319.34014 (32-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> 'foo'.encode('utf-32-be')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
LookupError: unknown encoding: utf-32-be
>>>
```

What's up with that?

**Comment by jdhardy** [comment]
Just an oversight.

**Comment by kunom** [comment]
With the current master:

```
IronPython 2.7.6.3 DEBUG (2.7.6.3) on .NET 4.0.30319.42000 (32-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> 'foo'.encode('utf-32-be')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Projekte\IronPython\External.LCA_RESTRICTED\Languages\IronPython\27\Lib\encodings\__init__.py", line 99, in search_function
  File "D:\Projekte\IronPython\External.LCA_RESTRICTED\Languages\IronPython\27\Lib\encodings\utf_32_be.py", line 8, in <module>
AttributeError: 'module' object has no attribute 'utf_32_be_encode'
```
