### ISSUE TITLE
`io.open` and `codecs.open` do not handle encoding errors correctly

### ISSUE THREAD

**Issue by pekkaklarck** [IronLanguages/main#1233]
Basically `io.open(p, encoding=e, errors='ignore').read()` fails if content cannot be decoded correctly but `open(p).read().decode(e, 'ignore')` works. Same occurs also with `codecs.open` and when using `'replace'` error handler.

To reproduce:
1. Have file with this content:
   
   ``` python
   import io
   import os
   
   path = 'test.txt'
   
   with open(path, 'wb') as f:
   f.write(u'hyv\xe4'.encode('UTF-8'))
   try:
   with open(path) as f:
       print 'open:'
       print f.read().decode('ASCII', 'ignore')
   with io.open(path, encoding='ASCII', errors='ignore') as f:
       print 'io.open:'
       print f.read()
   finally:
   os.remove(path)
   ```
2. When executed with Python:
   
   ```
   E:\>python io.open.bug.py
   open:
   hyv
   io.open:
   hyv
   ```
3. When executed with IronPython:
   
   ```
   E:\>ipy io.open.bug.py
   open:
   hyv
   io.open:
   Traceback (most recent call last):
   File "io.open.bug.py", line 18, in <module>
   File "c:\Program Files (x86)\IronPython 2.7\Lib\encodings\ascii.py", line 26, in decode
   UnicodeDecodeError: ('unknown', u'\xc3', 0, 1, '')
   ```

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#112
