### ISSUE TITLE
confusing error message - stack trace is missing a frame

### ISSUE THREAD

**Issue by paweljasinski** [IronLanguages/main#1238]
with-test.py

``` python
  1 def foo():
  2     with bar as open("foobar"):
  3         pass
  4
  5 foo()
```

cpython:

```
$ python with-test.py
  File "with-test.py", line 2
    with bar as open("foobar"):
SyntaxError: can't assign to function call
```

iron:

```
$ ipy with-test.py
Traceback (most recent call last):
  File "with-test.py", line 5, in <module>
SystemError: Operation is not valid due to the current state of the object.
```

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#111
