### ISSUE TITLE
tarfile.is_tarfile() raises IOError on non-tarfiles

### ISSUE THREAD

**Issue by marcusva** [IronLanguages/main#129]
The `tarfile.is_tarfile()` function within IronPython 2.7.4 raises an IOError when trying to open a file that is not a tar file. In CPython 2.7 it works without any problems.

The tarfile module is identical, further investigation shows that the behaviour of `bz2.BZ2File()` is different. In CPython, using `bz2.BZFile()` on an uncompressed file does not raise an exception. The CPython documentation also does not indicate that it shall raise an IOError (http://docs.python.org/2.7/library/bz2.html#bz2.BZ2File).

IronPython however raises an IOError, as shown below (using `tarfile.is_tarfile()`):

```
C:\projects\python-utils>c:\python27-x86\python.exe -c "import tarfile; print(tarfile.is_tarfile('C:\windows\win.ini'))"
False

C:\projects\python-utils>c:\IronPython-2.7.4\ipy.exe -c "import tarfile;
print(tarfile.is_tarfile('C:\windows\win.ini'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\IronPython-2.7.4\Lib\tarfile.py", line 2584, in is_tarfile
  File "c:\IronPython-2.7.4\Lib\tarfile.py", line 1658, in open
  File "c:\IronPython-2.7.4\Lib\tarfile.py", line 1744, in bz2open
IOError: System.IO.IOException: Not a valid BZip2 stream. byte 0, expected '66', got '59'
   bei Microsoft.Scripting.Runtime.LightExceptions.CheckAndThrow(Object value)
   bei Microsoft.Scripting.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
   bei Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
   bei Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   bei Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
   bei IronPython.Compiler.PythonCallTargets.OriginalCallTarget1(PythonFunction function, Object arg0)
   bei IronPython.Runtime.FunctionCaller`1.Call1(CallSite site, CodeContext context, Object func, T0 arg0)
   bei System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   bei Microsoft.Scripting.Interpreter.DynamicInstruction`4.Run(InterpretedFrame frame)
   bei Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   bei Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
   bei IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
   bei IronPython.Compiler.PythonScriptCode.Run(Scope scope)
   bei IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
   bei IronPython.Compiler.RuntimeScriptCode.Run(Scope scope)
   bei Microsoft.Scripting.Hosting.CompiledCode.Execute(ScriptScope scope)
   bei Microsoft.Scripting.Hosting.Shell.CommandLine.SimpleCommandDispatcher.Execute(CompiledCode compiledCode, ScriptScope scope)
   bei Microsoft.Scripting.Hosting.Shell.CommandLine.ExecuteCommand(ScriptSource source)
   bei IronPython.Hosting.PythonCommandLine.RunCommandWorker(String command)
   bei IronPython.Hosting.PythonCommandLine.RunCommand(String command)
```

Further investigation on the bz2 module:

```
C:\projects\python-utils>c:\python27-x86\python.exe -c "import bz2; print(bz2.BZ2File('C:\windows\win.ini'))"
<bz2.BZ2File object at 0x01DADD10>

C:\projects\python-utils>c:\IronPython-2.7.4\ipy.exe -c "import bz2; print(bz2.BZ2File('C:\windows\win.ini'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IOError: System.IO.IOException: Not a valid BZip2 stream. byte 0, expected '66', got '59'
   bei Ionic.BZip2.BZip2InputStream.CheckMagicChar(Char expected, Int32 position)
   bei Ionic.BZip2.BZip2InputStream.init()
   bei Ionic.BZip2.BZip2InputStream..ctor(Stream input, Boolean leaveOpen)
   bei Ionic.BZip2.BZip2InputStream..ctor(Stream input)
   bei IronPython.Modules.Bz2.Bz2Module.BZ2File.__init__(CodeContext context, String filename, String mode, Int32 buffering, Int32 compresslevel)
[...]
```

**Comment by slide** [comment]
This is still an issue that needs to be resolved.
