### ISSUE TITLE
2.7.6.3 get crash on my windows7 computer while working with eclipse

### ISSUE THREAD

**Issue by shiwee** [IronLanguages/main#1379]
I tried ipy.exe and ipy64.exe as interpreter, both crash, while the previous ironpython(2.7.5) works.

the eclipse version:
Version: Neon Release (4.6.0)
Build id: 20160613-1800

other information:
Faulting application name: ipy.exe, version: 2.7.6.1003, time stamp: 0x57b9a8dd
Faulting module name: clr.dll, version: 4.6.1076.0, time stamp: 0x56d7a0ff
Exception code: 0xc00000fd
Fault offset: 0x00010fee
Faulting process id: 0x17ac
Faulting application start time: 0x01d208dd6658ef8a
Faulting application path: C:\Program Files (x86)\IronPython 2.7\ipy.exe
Faulting module path: C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Report Id: a4d0cc4d-74d0-11e6-9a1a-b8aeed7f0c86

Faulting application name: ipy.exe, version: 2.7.6.1003, time stamp: 0x57b9a8dd
Faulting module name: IronPython.ni.dll, version: 2.7.6.1003, time stamp: 0x57b9a8d9
Exception code: 0xc00000fd
Fault offset: 0x002d0e91
Faulting process id: 0x126c
Faulting application start time: 0x01d208dd6be65f8a
Faulting application path: C:\Program Files (x86)\IronPython 2.7\ipy.exe
Faulting module path: C:\Windows\assembly\NativeImages_v4.0.30319_32\IronPython\5161bc351374575956b910bf5d008f7e\IronPython.ni.dll
Report Id: aa5b7d23-74d0-11e6-9a1a-b8aeed7f0c86

**Comment by simplicbe** [comment]
Are you just starting ipy.exe or do you execute any scripts etc?

**Comment by markusschaber** [comment]
"NativeImages" looks like the IronPython assembly might be precompiled using ngen.exe. Is that true? Could you try to disable ngen.exe for IronPython?

**Comment by shiwee** [comment]
@simplicbe the ipy.exe was invoked by eclipse I think. once I configured the interpreter, a dialog popup repeatedly.

**Comment by shiwee** [comment]
@markusschaber  not pretty sure but I downloaded from https://github.com/IronLanguages/main/releases/tag/ipy-2.7.6.3

**Comment by slide** [comment]
@markusschaber The installer will NGen the IronPython assemblies during the install. 

@shiwee Can you provide some additional information on your setup? Are you using PyDev? How do you have it configured?

**Comment by shiwee** [comment]
Sorry for slow response. I downloaded a 2.7.6.3(IronPython-2.7.6.3.zip), extract and put in drive e, then I go back to Eclipse, right click the ironpython project, choose "properties", then select "PyDev -Interpreter/Grammar" and "Click here to configure an interpreter not listed" to create a new one with the ipy downloaded. then the newly created as the Interpreter. 
then the issue reproduced.

**Comment by shiwee** [comment]
![Uploading ironpythonissue.png…]()

attached a screen snapshot, hope it help.

**Comment by shiwee** [comment]
![ironpythonissue](https://cloud.githubusercontent.com/assets/8911792/18428229/54dc3a48-78ff-11e6-824a-e3ad4deb22ba.png)
I finally have the screenshot uploaded.

**Comment by slide** [comment]
I notice you have Grammar version set to 3.0-3.5, can you please try setting it to 2.7 (or similar)?

**Comment by slide** [comment]
I tried this quickly the other day and it crashed for me as well. I didn't get a chance to dig into it though.

**Comment by iondiode** [comment]
Happening to me too :(

debug log from pydev/eclipse
```
 - Working Dir:
C:\Users\timowest\.p2\pool\plugins\org.python.pydev_5.5.0.201701191708\pysrc

 - OS:
Windows 7

 - Std output:


 - Err output:

Process is terminated due to StackOverflowException.


!STACK 0

java.io.IOException: An existing connection was forcibly closed by the remote host

	at sun.nio.ch.SocketDispatcher.read0(Native Method)

	at sun.nio.ch.SocketDispatcher.read(Unknown Source)

	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source)

	at sun.nio.ch.IOUtil.read(Unknown Source)

	at sun.nio.ch.SocketChannelImpl.read(Unknown Source)

	at sun.nio.ch.SocketAdaptor$SocketInputStream.read(Unknown Source)

	at sun.nio.ch.ChannelInputStream.read(Unknown Source)

	at java.io.InputStream.read(Unknown Source)

	at org.python.pydev.editor.codecompletion.shell.AbstractShell.read(AbstractShell.java:454)

	at org.python.pydev.editor.codecompletion.shell.AbstractShell.read(AbstractShell.java:506)

	at org.python.pydev.editor.codecompletion.shell.AbstractShell.writeAndGetResults(AbstractShell.java:692)

	at org.python.pydev.editor.codecompletion.shell.AbstractShell.internalChangePythonPath(AbstractShell.java:737)

	at org.python.pydev.editor.codecompletion.shell.AbstractShell.getImportCompletions(AbstractShell.java:755)

	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.createTokensFromServer(CompiledModule.java:373)

	at org.python.pydev.editor.codecompletion.revisited.modules.CompiledModule.<init>(CompiledModule.java:176)

	at org.python.pydev.editor.codecompletion.revisited.SystemModulesManager.getBuiltinModule(SystemModulesManager.java:332)

	at org.python.pydev.editor.codecompletion.revisited.SystemModulesManager.getModule(SystemModulesManager.java:371)

	at com.python.pydev.analysis.additionalinfo.AbstractAdditionalDependencyInfo.updateKeysIfNeededAndSave(AbstractAdditionalDependencyInfo.java:256)

	at com.python.pydev.analysis.system_info_builder.InterpreterInfoBuilder.syncInfoToPythonPath(InterpreterInfoBuilder.java:154)

	at com.python.pydev.analysis.system_info_builder.InterpreterInfoBuilder.syncInfoToPythonPath(InterpreterInfoBuilder.java:80)

	at org.python.pydev.editor.codecompletion.revisited.SynchSystemModulesManager.synchronizeManagerToNameToInfoPythonpath(SynchSystemModulesManager.java:390)

	at org.python.pydev.editor.codecompletion.revisited.SyncSystemModulesManagerScheduler$SynchJob.run(SyncSystemModulesManagerScheduler.java:261)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)



!ENTRY org.python.pydev.shared_core 4 4 2017-03-03 15:07:43.854

!MESSAGE ERROR reading shell.
ProcessInfo:

 - Executed: C:\Program Files (x86)\IronPython 2.7\ipy64.exe -X:Frames C:\Users\timowest\.p2\pool\plugins\org.python.pydev_5.5.0.201701191708\pysrc\pycompletionserver.py 64052```

**Comment by slide** [comment]
I was unable to determine why this was happening back in November. I could look again soon.

**Comment by iondiode** [comment]
running this command at prompt gave 

```
C:\Users\timowest> "C:\Program Files (x86)\IronPython 2.7\ipy.exe" -X:Frames "C:
\Users\timowest\Documents\eclipse_java_dev\eclipse\plugins\org.python.pydev_3.4.
1.201403181715\pysrc\pycompletionserver.py" 53089
pycompletionserver will start
pycompletionserver connecting to java server on 127.0.0.1 (53089)
Error on connectToServer with parameters: host: 127.0.0.1 port: 53089
pycompletionserver received error: Traceback (most recent call last):
  File "C:\Users\timowest\Documents\eclipse_java_dev\eclipse\plugins\org.python.
pydev_3.4.1.201403181715\pysrc\pycompletionserver.py", line 249, in run
    self.connectToServer()
  File "C:\Users\timowest\Documents\eclipse_java_dev\eclipse\plugins\org.python.
pydev_3.4.1.201403181715\pysrc\pycompletionserver.py", line 195, in connectToSer
ver
    s.connect((HOST, self.port))
error: [Errno 10061] No connection could be made because the target machine acti
vely refused it 127.0.0.1:53089

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files (x86)\IronPython 2.7\Lib\threading.py", line 801, in _T
hread__bootstrap_inner
    self.run()
  File "C:\Users\timowest\Documents\eclipse_java_dev\eclipse\plugins\org.python.
pydev_3.4.1.201403181715\pysrc\pycompletionserver.py", line 249, in run
    self.connectToServer()
  File "C:\Users\timowest\Documents\eclipse_java_dev\eclipse\plugins\org.python.
pydev_3.4.1.201403181715\pysrc\pycompletionserver.py", line 195, in connectToSer
ver
    s.connect((HOST, self.port))
error: [Errno 10061] No connection could be made because the target machine acti
vely refused it 127.0.0.1:53089
```
But it seems to be ok if i start a dummy server on that port (eg nc -l 53089)  yields

```
C:\Users\timowest> "C:\Program Files (x86)\IronPython 2.7\ipy.exe" -X:Frames "C:
\Users\timowest\Documents\eclipse_java_dev\eclipse\plugins\org.python.pydev_3.4.
1.201403181715\pysrc\pycompletionserver.py" 53089
pycompletionserver will start
pycompletionserver connecting to java server on 127.0.0.1 (53089)
pycompletionserver Connected to java server
```
