### ISSUE TITLE
ipy2.7.6.3 with mono on Ubuntu 12.04: error message about importing _sysconfigdata

### ISSUE THREAD

**Issue by chschmitt** [IronLanguages/main#1386]
Running IronPython 2.7.6.3 with mono on Ubuntu 12.04. displays the following error:

```
$ mono ipy.exe
Traceback (most recent call last):
  File "/run/shm/IronPython-2.7.6.3/Lib/site.py", line 552, in <module>
  File "/run/shm/IronPython-2.7.6.3/Lib/site.py", line 534, in main
  File "/run/shm/IronPython-2.7.6.3/Lib/site.py", line 266, in addusersitepackages
  File "/run/shm/IronPython-2.7.6.3/Lib/site.py", line 241, in getusersitepackages
  File "/run/shm/IronPython-2.7.6.3/Lib/site.py", line 231, in getuserbase
  File "/run/shm/IronPython-2.7.6.3/Lib/sysconfig.py", line 522, in get_config_var
  File "/run/shm/IronPython-2.7.6.3/Lib/sysconfig.py", line 474, in get_config_vars
  File "/run/shm/IronPython-2.7.6.3/Lib/sysconfig.py", line 358, in _init_posix
ImportError: No module named _sysconfigdata
IronPython 2.7.6.3 (2.7.6.3) on Mono 4.0.30319.1 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

I also checked IronPython 2.7.5, which starts normally.

**Comment by slide** [comment]
I have a possible fix for this, I'll try it on my Linux box soon and see if it does work.

**Comment by slide** [comment]
This should be fixed as part of https://github.com/IronLanguages/main/pull/1410

**Comment by slide** [comment]
Fixed in https://github.com/IronLanguages/main/pull/1410
