### ISSUE TITLE
Slicing a memoryview produces wrong results

### ISSUE THREAD

**Issue by chschmitt** [IronLanguages/main#1387]
The slicing behaviour of `memoryview` objects is buggy. See the test case below (tested with 2.7.5 and 2.7.6.3). The memoryview may report a wrong length and/or return wrong data.

```
import unittest

class TestMemoryView(unittest.TestCase):
    data = bytearray(xrange(10))
    mview = memoryview(data)

    def testMemoryViewEmptySliceData(self):
        chunk = self.mview[-1:2]
        chunk_data = bytearray(chunk)
        self.assertEqual(chunk_data, bytearray(0))

    def testMemoryViewEmptySliceLength(self):
        chunk = self.mview[-1:2]
        self.assertEqual(len(chunk), 0)

    def testMemoryViewTruncatedSliceData(self):
        chunk = self.mview[8:12]
        chunk_data = bytearray(chunk)
        self.assertEqual(chunk_data, bytearray([8,9]))

    def testMemoryViewTruncatedSliceLength(self):
        chunk = self.mview[8:12]
        self.assertEqual(len(chunk), 2)

if __name__ == '__main__':
    unittest.main()
```

Results:

```
FF.F
======================================================================
FAIL: testMemoryViewEmptySliceData (__main__.TestMemoryView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/test_memview.py", line 10, in testMemoryViewEmptySliceData
    self.assertEqual(chunk_data, bytearray(0))
AssertionError: bytearray(b'\t\x00\x01') != bytearray(b'')

======================================================================
FAIL: testMemoryViewEmptySliceLength (__main__.TestMemoryView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/test_memview.py", line 14, in testMemoryViewEmptySliceLength
    self.assertEqual(len(chunk), 0)
AssertionError: 3 != 0

======================================================================
FAIL: testMemoryViewTruncatedSliceLength (__main__.TestMemoryView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/test_memview.py", line 23, in testMemoryViewTruncatedSliceLength
    self.assertEqual(len(chunk), 2)
AssertionError: 4 != 2

----------------------------------------------------------------------
Ran 4 tests in 0.068s

FAILED (failures=3)
```

**Comment by kunom** [comment]
Slicing in MemoryView is clearly broken with regard to negative index numbers. It is not clear why the implementation does not use the `Slice.indices()` method for proper range calculation.

The _test_memoryview_cpy_ and _test_bytes_cpy_ tests would also, based on a quick glance, cover these checks, but are currently disabled in the test suite because of they are failing...
