### ISSUE TITLE
ironpython 2.7 : exposing a dynamic object to python unexpected behavior

### ISSUE THREAD

**Issue by ch-hristov** [IronLanguages/main#1401]
If I try to expose an anonymous object to a python script through a hosted environment, I cannot access the members of the provided variable through python, it throws a MissingMemberException.

Example project : 

https://github.com/interdrift/ipanonbug

**Comment by kunom** [comment]
``` c#
var engine = Python.CreateEngine();

var scope = engine.CreateScope();
scope.SetVariable("item", new { x = 1.0 });

var scriptSrc = engine.CreateScriptSourceFromString("print(item.x)");
scriptSrc.Execute(scope);
```

Exception with IronPython 2.7.5:

```
System.MissingMemberException was unhandled
  HResult=-2146233070
  Message='<>f__AnonymousType0[float]' object has no attribute 'x'
  Source=IronPython
  StackTrace:
       at IronPython.Runtime.Binding.PythonGetMemberBinder.FastErrorGet`1.GetError(CallSite site, TSelfType target, CodeContext context)
       at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
       at Microsoft.Scripting.Interpreter.DynamicInstruction`3.Run(InterpretedFrame frame)
       at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
       at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
       at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
       at IronPython.Compiler.PythonScriptCode.Run(Scope scope)
       at IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
       at IronPython.Compiler.RuntimeScriptCode.Run(Scope scope)
       at Microsoft.Scripting.SourceUnit.Execute(Scope scope, ErrorSink errorSink)
       at Microsoft.Scripting.Hosting.ScriptSource.Execute(ScriptScope scope)
       at IronPythonAnnonymousTypeBug.Program.Main(String[] args) in D:\mytemp\tmp9\ipanonbug\IronPythonAnnonymousTypeBug\Program.cs:line 15
       [...]
```

**Comment by kunom** [comment]
IronPython currently decides that even though `x` is declared as public, it should not be treated as such because there is no path A.x with A being a public base type of the anonymous type. This looks very wrong here, but I still have to investigate for which other situation it was intended for.

As a workaround, you can use 

``` c#
var engine = Python.CreateEngine(new Dictionary<string, object> { { "PrivateBinding", true } });
```

**Comment by ch-hristov** [comment]
@kunom I see that private binding would allow the user to access private fields of .net objects. I want to avoid this. Could you perhaps help me navigate to the code that decides which members will be serialized to python as public?

**Comment by kunom** [comment]
See the _CompilerHelpers_ class.

The issue here is to find a way to determine at runtime whether a private class is an anonymous class or not. The only way I found that goes in that direction is to check for the `CompilerGenerated` custom attribute.

It might be beneficial to look at the C# implementation of the `dynamic` keyword:

``` c#
public static class Component
{
    public interface IA { int a { get; set; } }
    private class A : IA { public int a { get; set; } public int b { get; set; } }
    public static IA CreateIA() { return new A(); }
    public static object CreateAnon() { return new { a = 3 }; }
}

dynamic a = Component.CreateIA();
var aa = a.a; // fails with C#, works with IPY
var ab = a.b; // fails with C#, fails with IPY

dynamic b = Component.CreateAnon();
var ba = b.a; // works with C#, should also work with IPY
```

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#95
