### ISSUE TITLE
RC 2.7.7 rc1 regression - subprocess+fdopen

### ISSUE THREAD

**Issue by ita1024** [IronLanguages/main#1488]
I am getting the following exception in a semi-random manner:

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Program Files (x86)\IronPython 2.7\Lib\threading.py", line 801, in _Thread__bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\IronPython 2.7\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Program Files (x86)\IronPython 2.7\Lib\subprocess.py", line 1044, in _readerthread
    buffer.append(fh.read())
ValueError: I/O operation on closed file

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files (x86)\IronPython 2.7\Lib\threading.py", line 801, in _Thread__bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\IronPython 2.7\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "test.py", line 34, in fork
    out, err= proc.communicate()
  File "C:\Program Files (x86)\IronPython 2.7\Lib\subprocess.py", line 830, in communicate
    return self._communicate(input)
  File "C:\Program Files (x86)\IronPython 2.7\Lib\subprocess.py", line 1088, in _communicate
    stdout = stdout[0]
IndexError: index out of range: 0
```

The following testcase can reproduce the problem relatively reliably. It has one thread creating subprocesses, one thread writing a file, and a control thread to stop the script after 10 seconds:

``` python
import subprocess, threading, os, time

orig = time.time()
is_stop = False

def write_win32(f, data, m='w', encoding='ISO8859-1'):
        flags = os.O_CREAT | os.O_TRUNC | os.O_WRONLY | os.O_NOINHERIT
        try:
                fd = os.open(f, flags)
        except OSError:
                raise OSError('Cannot write to %r' % f)
        f = os.fdopen(fd, m)
        try:
                f.write(data)
        finally:
                f.close()

def write(name, data):
        with open(name, 'w') as f:
                f.write(data)
def writer():
        global is_stop
        while not is_stop:
                write_win32('foo.h', str(time.time()))

def forker():
        global is_stop
        while not is_stop:
                proc = subprocess.Popen(["C:/Python34/python.exe", "--help"], shell=True,
                        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
                out, err= proc.communicate()

def timer():
        global is_stop, orig
        while True:
                delta = time.time() - orig
                time.sleep(0.1)
                if delta > 10:
                        is_stop = True
                        break

t1 = threading.Thread(target=forker)
t2 = threading.Thread(target=writer)
t3 = threading.Thread(target=timer)

threads = [t1, t2, t3]
for t in threads:
        t.start()
for t in threads:
        t.join()
```

The error does not appear when replacing `write_win32` by `write`. With `os.O_NOINHERIT` the subprocess is not supposed to get a file handle; this is unnecessary in Python < 3.4 because subprocesses inheriting the file handles on windows will keep them open and cause a variety of errors. Also, the same error is observed after changing `f.close()` by `os.close(fd)`

**Comment by slozier** [comment]
This one is fixed with #1490.
