### ISSUE TITLE
Obscure inheritance problem with WinForms Controls

### ISSUE THREAD

**Issue by andygraham** [IronLanguages/main#1541]
I noticed this some time ago when I was writing my own (semi) graphical WinForms based debugger for IronPython and as IronPython is now under further development I thought that I would report this in case there are any further implications of this problem.

I was reflecting  on an instance of a WinForms Control using dir() and using getattr()  to get the values of properties. I found three properties that give path based exceptions in an IronPython Class that inherits from a Control. In fact accessing these properties directly also, unsurprisingly, gives the same error,
```
import clr
clr.AddReference('System.Windows.Forms')
from System.Windows.Forms import Form

form1 = Form()
print form1.Height # OK
print form1.CompanyName # OK
print form1.ProductName # OK
print form1.ProductVersion # OK

class MyForm(Form):
    pass
    
form2 = MyForm()
print form2.Height # OK
print form2.CompanyName # Error
print form2.ProductName # Error
print form2.ProductVersion # Error
```

I guess this falls into the far nether reaches of obscurity and priority and I work round it by trapping and ignoring the errors.

**Comment by kunom** [comment]
Stacktrace printed using `-X:ExceptionDetail`:

```
Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.Security.Permissions.FileIOPermission.CheckIllegalCharacters(String[] str)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path)
   at System.Windows.Forms.Control.ControlVersionInfo.GetFileVersionInfo()
   at System.Windows.Forms.Control.ControlVersionInfo.get_CompanyName()
   at IronPython.NewTypes.System.Windows.Forms.Form_4$4.#base#get_CompanyName()
   [...]   
```

ILSpy about `ControlVersionInfo.GetFileVersionInfo` (simplified):

``` c#
var fullyQualifiedName = this.owner.GetType().Module.FullyQualifiedName;
new FileIOPermission(FileIOPermissionAccess.Read, fullyQualifiedName).Assert();
```

**Comment by kunom** [comment]
``` python
print form1.GetType().Module.FullyQualifiedName
print form2.GetType().Module.FullyQualifiedName
```

produces

```
C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll
<In Memory Module>
```

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#78
