### ISSUE TITLE
`ensurepip` fails on latest version

### ISSUE THREAD

**Issue by devkhan** [IronLanguages/main#1566]
Using latest(2.7.7) IronPython, trying to install `pip`, the following happens:

```
$ mono ipy64.exe -X:Frames -m pip install youtube-dl
Traceback (most recent call last):
  File "/Users/.../IronPython-2.7.6.3/Lib/site.py", line 552, in <module>
  File "/Users/.../IronPython-2.7.6.3/Lib/site.py", line 534, in main
  File "/Users/.../IronPython-2.7.6.3/Lib/site.py", line 266, in addusersitepackages
  File "/Users/.../IronPython-2.7.6.3/Lib/site.py", line 241, in getusersitepackages
  File "/Users/.../IronPython-2.7.6.3/Lib/site.py", line 231, in getuserbase
  File "/Users/.../IronPython-2.7.6.3/Lib/sysconfig.py", line 522, in get_config_var
  File "/Users/.../IronPython-2.7.6.3/Lib/sysconfig.py", line 474, in get_config_vars
  File "/Users/.../IronPython-2.7.6.3/Lib/sysconfig.py", line 358, in _init_posix
ImportError: No module named _sysconfigdata
Unhandled exception:
Traceback (most recent call last):
  File "/Users/.../IronPython-2.7.6.3/Lib/runpy.py", line 182, in run_module
  File "/Users/.../IronPython-2.7.6.3/Lib/runpy.py", line 107, in _get_module_details
ImportError: No module named pip
```

Mono details:

```
$ mono -V
Mono JIT compiler version 4.8.0 (mono-4.8.0-branch/9e8f0ee Wed Jan  4 15:06:01 EST 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug
	LLVM:          yes(3.6.0svn-mono-master/8b1520c)
	GC:            sgen
```

Operating system: macOS Sierra (10.12) Beta 7

**Comment by matthewblott** [comment]
Personally I've never been able to get ```pip``` to run using Mono - this looks the same as [# 1243](https://github.com/IronLanguages/main/issues/1243).

**Comment by slide** [comment]
Agreed

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#77
