### ISSUE TITLE
Using pip fails with `IndexError: index out of range: -1`

### ISSUE THREAD

**Issue by pekkaklarck** [IronLanguages/main#1572]
After installing IronPython 2.7.7 and running `ipy -X:Frames -m ensurepip`, trying to install a package or just check the installed pip version fails like this:

```
C:\Windows\system32>ipy -X:Frames -m pip install robotframework
Unhandled exception:
Traceback (most recent call last):
  File "c:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 182, in run_module
  File "c:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\pyparsing.py", line 1261, in setParseAction
  File "c:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\pyparsing.py", line 1043, in _trim_arity
  File "c:\Program Files (x86)\IronPython 2.7\Lib\runpy.py", line 111, in _get_module_details
  File "c:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\__init__.py", line 26, in <module>
  File "c:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\utils\__init__.py", line 27, in <module>
  File "c:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 74, in <module>
  File "c:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\packaging\requirements.py", line 9, in <module>
  File "c:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\pyparsing.py", line 4715, in <module>
IndexError: index out of range: -1
```
Same problem if I just try to check installed pip version with `--version` or run the installed `pip.exe` directly.

**Comment by pekkaklarck** [comment]
Same problem also if I run the installed `pip.exe` directly.

**Comment by slozier** [comment]
I haven't been able to reproduce this using the steps provided (install IronPython 2.7.7, run ensure pip and then "try to do anything with pip").

After hitting the same issue while investigating #1573 I did boil it down to a simple repro case which does not invlove pyparsing: https://github.com/IronLanguages/main/issues/1573#issuecomment-277086607

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#71
