### ISSUE TITLE
install numpy, but AttributeError: 'module' object has no attribute '_getframe'

### ISSUE THREAD

**Issue by whaozl** [IronLanguages/main#1580]
```
D:\IronPython-2.7.7-win\Scripts>ipy -X:Frames -m pip install numpy
Collecting numpy
D:\IronPython-2.7.7-win\Lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:1: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  from __future__ import absolute_import
  Using cached numpy-1.12.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\IronPython-2.7.7-win\Lib\site-packages\setuptools\__init__.py", line 11, in <module>
      File "D:\IronPython-2.7.7-win\Lib\site-packages\setuptools\extern\__init__.py", line 1, in <module>
      File "D:\IronPython-2.7.7-win\Lib\site-packages\pkg_resources\__init__.py", line 46, in <module>
      File "D:\IronPython-2.7.7-win\Lib\site-packages\pkg_resources\extern\__init__.py", line 42, in load_module
      File "D:\IronPython-2.7.7-win\Lib\site-packages\pkg_resources\_vendor\six.py", line 701, in <module>
      File "D:\IronPython-2.7.7-win\Lib\site-packages\pkg_resources\_vendor\six.py", line 692, in exec_
    AttributeError: 'module' object has no attribute '_getframe'
    ----------------------------------------
```
And, I udpate the pip to pip9.0.1 by:
```python
ipy64 -X:FullFrames -m pip install --upgrade pip
```
Then, install the numpy:
```
D:\IronPython-2.7.7-win\Scripts>ipy64 -X:FullFrames -m pip install numpy
Unhandled exception:
Traceback (most recent call last):
  File "D:\IronPython-2.7.7-win\Lib\runpy.py", line 182, in run_module
  File "D:\IronPython-2.7.7-win\Lib\site-packages\pip\_vendor\pyparsing.py", line 1261, in setParseAction
  File "D:\IronPython-2.7.7-win\Lib\site-packages\pip\_vendor\pyparsing.py", line 1043, in _trim_arity
  File "D:\IronPython-2.7.7-win\Lib\runpy.py", line 111, in _get_module_details
  File "D:\IronPython-2.7.7-win\Lib\site-packages\pip\__init__.py", line 26, in <module>
  File "D:\IronPython-2.7.7-win\Lib\site-packages\pip\utils\__init__.py", line 27, in <module>
  File "D:\IronPython-2.7.7-win\Lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 74, in <module>
  File "D:\IronPython-2.7.7-win\Lib\site-packages\pip\_vendor\packaging\requirements.py", line 9, in <module>
  File "D:\IronPython-2.7.7-win\Lib\site-packages\pip\_vendor\pyparsing.py", line 4715, in <module>
IndexError: index out of range: -1
```

**Comment by moshearuch** [comment]
The same with google-apputils.

**Comment by slide** [comment]
We currently ship with a specific version of pip that we have tested with IronPython (arguments as to whether it works with all packages is still up in ther air). We are enabling frames by default in the next release, but please don't upgrade pip.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#70
