### ISSUE TITLE
Error installing pip packages

### ISSUE THREAD

**Issue by jenokizm** [IronLanguages/main#1601]
I need to set it permissible pystun. (https://pypi.python.org/pypi/pystun)
i now run cmd command:
`ipy -X:Frames -m pip install pystun`
but i have error output:
```
Collecting pystun
C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\requests\pac
kages\urllib3\util\ssl_.py:1: SNIMissingWarning: An HTTPS request has been made,
 but the SNI (Subject Name Indication) extension to TLS is not available on this
 platform. This may cause the server to present an incorrect TLS certificate, wh
ich can cause validation failures. For more information, see https://urllib3.rea
dthedocs.org/en/latest/security.html#snimissingwarning.
  from __future__ import absolute_import
C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\_vendor\requests\pac
kages\urllib3\connection.py:1: SubjectAltNameWarning: Certificate for pypi.pytho
n.org has no `subjectAltName`, falling back to check for a `commonName` for now.
 This feature is being removed by major browsers and deprecated by RFC 2818. (Se
e https://github.com/shazow/urllib3/issues/497 for details.)
  from __future__ import absolute_import
Exception:
Traceback (most recent call last):
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\basecommand.
py", line 209, in main
    status = self.run(options, args)
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\commands\ins
tall.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\req\req_set.
py", line 356, in prepare_files
    discovered_reqs.extend(self._prepare_file(
  File "C:\Program Files (x86)\IronPython 2.7\Lib\contextlib.py", line 35, in __
exit__
    self.gen.throw(type, value, traceback)
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pip\utils\loggin
g.py", line 36, in indent_log
    yield
ValueError: too many values to unpack
```

**Comment by Varbin** [comment]
Same here (while upgrading pip). My log:
```
PS C:\> C:\IronPython27\ipy64.exe -X:Frames -m pip install -U pip
C:\IronPython27\Lib\site-packages\pip\_vendor\requests\packages\urllib3\util\ssl_.py:1: SNIMissingWarning: An HTTPS requ
est has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may ca
use the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see h
ttps://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  from __future__ import absolute_import
C:\IronPython27\Lib\site-packages\pip\_vendor\requests\packages\urllib3\connection.py:1: SubjectAltNameWarning: Certific
ate for pypi.python.org has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being
 removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  from __future__ import absolute_import
Exception:
Traceback (most recent call last):
  File "C:\IronPython27\Lib\site-packages\pip\basecommand.py", line 209, in main
    status = self.run(options, args)
  File "C:\IronPython27\Lib\site-packages\pip\commands\install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "C:\IronPython27\Lib\site-packages\pip\req\req_set.py", line 356, in prepare_files
    discovered_reqs.extend(self._prepare_file(
  File "C:\IronPython27\Lib\site-packages\pip\req\req_set.py", line 447, in _prepare_file
    skip_reason = self._check_skip_installed(
  File "C:\IronPython27\Lib\site-packages\pip\req\req_set.py", line 397, in _check_skip_installed
    finder.find_requirement(req_to_install, self.upgrade)
  File "C:\IronPython27\Lib\site-packages\pip\index.py", line 440, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "C:\IronPython27\Lib\site-packages\pip\index.py", line 398, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "C:\IronPython27\Lib\site-packages\pip\index.py", line 543, in _get_pages
    page = self._get_page(location)
  File "C:\IronPython27\Lib\site-packages\pip\index.py", line 646, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "C:\IronPython27\Lib\site-packages\pip\index.py", line 750, in get_page
    resp = session.get(
  File "C:\IronPython27\Lib\site-packages\pip\_vendor\requests\sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "C:\IronPython27\Lib\site-packages\pip\download.py", line 378, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "C:\IronPython27\Lib\site-packages\pip\_vendor\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\IronPython27\Lib\site-packages\pip\_vendor\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\IronPython27\Lib\site-packages\pip\_vendor\cachecontrol\adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "C:\IronPython27\Lib\site-packages\pip\_vendor\requests\adapters.py", line 366, in send
    resp = conn.urlopen(
  File "C:\IronPython27\Lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 557, in urlopen

    httplib_response = self._make_request(conn, method, url,
  File "C:\IronPython27\Lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 345, in _make_r
equest
    self._validate_conn(conn)
  File "C:\IronPython27\Lib\site-packages\pip\_vendor\requests\packages\urllib3\connectionpool.py", line 784, in _valida
te_conn
    conn.connect()
  File "C:\IronPython27\Lib\site-packages\pip\_vendor\requests\packages\urllib3\connection.py", line 277, in connect
    match_hostname(cert, asserted_hostname)
  File "C:\IronPython27\Lib\ssl.py", line 262, in match_hostname
    for key, value in sub:
ValueError: too many values to unpack
```

**Comment by Varbin** [comment]
@jenokizm You may try a manual installation: Downloding the Tarball, extracting it (with e.g. 7z or WinRAR) and run `ipy -X:Frames setup.py install`. But you MUST install all dependencies before otherwise it will try to download it (which does obvisously not work).

**Comment by slide** [comment]
Please don't upgrade pip, we have a specific version that we package with ironpython right now,

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#57
