### ISSUE TITLE
console output order

### ISSUE THREAD

**Issue by Frame42** [IronLanguages/main#1632]
In the python console, stderr and stdout happen out of order. This can be confusing if you are debugging or encounter an error. The following code gives me the interleaved output below.
```import inspect
def C():
    staTup = inspect.stack(1)
    print("\n".join(map(str,zip(dir(staTup),map(lambda x:getattr(staTup,x),dir(staTup))))))
    raise Exception()
```

```
Traceback (most recent call last):
('__add__', <built-in method __add__ of list object at 0x000000000000006C>)
  File "C:/scratches/scratch.py", line 27, in <module>
('__class__', <type 'list'>)
  File "C:/scratches/scratch.py", line 21, in C
('__contains__', <built-in method __contains__ of list object at 0x000000000000006C>)
Exception
('__delattr__', <built-in method __delattr__ of list object at 0x000000000000006C>)
('__delitem__', <built-in method __delitem__ of list object at 0x000000000000006C>)
('__delslice__', <built-in method __delslice__ of list object at 0x000000000000006C>)
('__doc__', 'list()\r\n')
('__eq__', <built-in method __eq__ of list object at 0x000000000000006C>)
('__format__', <built-in method __format__ of list object at 0x000000000000006C>)
('__ge__', <built-in method __ge__ of list object at 0x000000000000006C>)
('__getattribute__', <built-in method __getattribute__ of list object at 0x000000000000006C>)
('__getitem__', <built-in method __getitem__ of list object at 0x000000000000006C>)
('__getslice__', <built-in method __getslice__ of list object at 0x000000000000006C>)
('__gt__', <built-in method __gt__ of list object at 0x000000000000006C>)
('__hash__', None)
('__iadd__', <built-in method __iadd__ of list object at 0x000000000000006C>)
('__imul__', <built-in method __imul__ of list object at 0x000000000000006C>)
('__init__', <built-in method __init__ of list object at 0x000000000000006C>)
('__iter__', <built-in method __iter__ of list object at 0x000000000000006C>)
('__le__', <built-in method __le__ of list object at 0x000000000000006C>)
('__len__', <built-in method __len__ of list object at 0x000000000000006C>)
('__lt__', <built-in method __lt__ of list object at 0x000000000000006C>)
('__mul__', <built-in method __mul__ of list object at 0x000000000000006C>)
('__ne__', <built-in method __ne__ of list object at 0x000000000000006C>)
('__new__', <built-in function __new__>)
('__radd__', <built-in method __radd__ of list object at 0x000000000000006C>)
('__reduce__', <built-in method __reduce__ of list object at 0x000000000000006C>)
('__reduce_ex__', <built-in method __reduce_ex__ of list object at 0x000000000000006C>)
('__repr__', <built-in method __repr__ of list object at 0x000000000000006C>)
('__reversed__', <built-in method __reversed__ of list object at 0x000000000000006C>)
('__rmul__', <built-in method __rmul__ of list object at 0x000000000000006C>)
('__setattr__', <built-in method __setattr__ of list object at 0x000000000000006C>)
('__setitem__', <built-in method __setitem__ of list object at 0x000000000000006C>)
('__setslice__', <built-in method __setslice__ of list object at 0x000000000000006C>)
('__sizeof__', <built-in method __sizeof__ of list object at 0x000000000000006C>)
('__str__', <built-in method __str__ of list object at 0x000000000000006C>)
('__subclasshook__', <built-in method __subclasshook__ of list object at 0x000000000000006C>)
('append', <built-in method append of list object at 0x000000000000006C>)
('count', <built-in method count of list object at 0x000000000000006C>)
('extend', <built-in method extend of list object at 0x000000000000006C>)
('index', <built-in method index of list object at 0x000000000000006C>)
('insert', <built-in method insert of list object at 0x000000000000006C>)
('pop', <built-in method pop of list object at 0x000000000000006C>)
('remove', <built-in method remove of list object at 0x000000000000006C>)
('reverse', <built-in method reverse of list object at 0x000000000000006C>)
('sort', <built-in method sort of list object at 0x000000000000006C>)
```
The interrupt trace is never at the same place while CPython always renders it at the end of the first buffer. Is this an intended behavior ?

**Comment by slozier** [comment]
I'm not getting the interleaved behaviour over here. Can you give a bit more info about your setup so we can try to reproduce?

**Comment by Frame42** [comment]
IronPython 2.7.7 (2.7.7.0) on .NET 4.0.30319.42000 (32-bit)
I just noticed, there is no interleave in the command line, only if I run the script inside Pycharm 2017.1.2.
