### ISSUE TITLE
TypeError: Unable to cast object of type 'Microsoft.Scripting.Runtime.Uninitialized' to type 'System.Exception' when using -X:Tracing

### ISSUE THREAD

**Issue by Schoepe** [IronLanguages/main#208]
Minimal code is:

import mimetypes
mimetypes.guess_type("test.txt")

When running all seems fine but running it with -X:Tracing leads to:

TypeError: Unable to cast object of type 'Microsoft.Scripting.Runtime.Uninitialized' to type 'System.Exception'.

**Comment by markusschaber** [comment]
It also works when the script itself sets a trace handler, without setting -X:Tracing from outside:
```txt
C:\Program Files (x86)\IronPython 2.7>ipy.exe
IronPython 2.7.5 (2.7.5.0) on .NET 4.0.30319.34209 (32-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> def trace(*args, **kwargs):
...     return trace
...
>>> trace
<function trace at 0x000000000000002B>
>>> sys.settrace(trace)
>>> import mimetypes
>>> mimetypes.guess_type("test.txt")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\Lib\mimetypes.py", line 294, in guess_type
  File "C:\Program Files (x86)\IronPython 2.7\Lib\mimetypes.py", line 355, in init
  File "C:\Program Files (x86)\IronPython 2.7\Lib\mimetypes.py", line 259, in read_windows_registry
  File "C:\Program Files (x86)\IronPython 2.7\Lib\mimetypes.py", line 245, in enum_types
TypeError: Das Objekt des Typs "Microsoft.Scripting.Runtime.Uninitialized" kann nicht in Typ "System.Exception" umgewandelt werden.
```
